export const fakeJobs = [
    {
        "id": 1,
        "jobCode": "1430",
        "title": "Bone/Bio Specialist",
        "description": "<p><span style=\"color: rgb(143, 204, 69);\">Job Description</span></p><p>The Bone Biologics Specialist will be responsible for driving business development initiatives, establishing partnerships and</p><p>expanding market presence for our bone biologics products on the West coast. Reporting to the National Sales Director, this</p><p>position will play a pivotal role in achieving sales targets, expanding market share, and fostering strong customer</p><p>relationships.</p><p><span style=\"color: rgb(143, 204, 69);\">Products</span></p><p><a href=\"https://sanaramedtech.com/surgical/\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(74, 161, 255);\">Surgical Product Line</a></p><p><span style=\"color: rgb(143, 204, 69);\">Minimum Requirements</span></p><ul><li>Minimum education required for competent performance:</li><li>Bachelors degree in Business Administration, Marketing or related field (MBA preferred)&nbsp;</li><li>5+ years of experience in a sales leadership role with a proven track record of success in a medical device or&nbsp;pharmaceutical sales role</li><li>Industry Knowledge – Experience in selling complex medical technologies or solutions, with a deep understanding of&nbsp;the regulatory landscape.</li><li>Leadership Excellence – Strong leadership skills with the ability to inspire and motivate a team.</li><li>Analytical skills – Analytical mindset with proficiency in sales data analysis and forecasting.</li><li>Oral Communication – Excellent communication, negotiation, and presentation skills.</li><li>Initiative – Takes independent actions and calculated risks; self-motivated &amp;amp; looks for and takes&nbsp;advantages of opportunities; asks for and offers help when needed.</li><li>Customer Focus – Customer-centric mindset with a strong focus on understanding customer needs and delivering&nbsp;solutions that meet or exceed expectations.</li><li>Collaboration – Team player; effectively works with other departments and team members to resolve&nbsp;discrepancies.</li><li>Ethical Conduct – Demonstrated commitment to ethical business practices and compliance with industry regulations.</li></ul><p><span style=\"color: rgb(143, 204, 69);\">Job Requirements</span></p><ul><li>Identify distributors specializing in bone biologics sales and qualify each based&nbsp;on good relationships and reputation within facilities.</li><li>Submit distributors of interest to National Sales Director for final approval and&nbsp;begin contracting process.</li><li>Distributor training to be conducted in conjunction with the clinical manager or&nbsp;by the National Business Development Director and will include product and disease&nbsp;state reviews.</li><li>Certify distributor competency in selling Sanara MedTech products lines by&nbsp;partnering with them while calling on customers.</li><li>Conduct on-going training, supply literature, samples, and trunk stock inventory.</li><li>Additional support could include, but is not limited to, regular business review&nbsp;meetings, physician meetings, dinner programs and corporate updates.</li><li>Priority for the Bone Biologics Specialist position. Sell the entire Ortho Bio&nbsp;portfolio through distributor or direct relationships.</li><li>Establish and maintain relationships with key stakeholders in focus accounts,&nbsp;this includes but is not limited to surgeons, OR staff and C-suite personnel.</li><li>Territory relationships are the responsibility of the Bone Biologics Specialist in&nbsp;order to provide continuity regardless of the distributor relationships in place.</li><li>Appropriate sales techniques are expected. Sales leadership will require the&nbsp;Bone Biologics Specialist to utilize a structured sales approach based on the&nbsp;needs, opportunities, and growth objectives that have been outlined for their</li><li>respective territory.</li><li>The Bone Biologics Specialist should identify key opinion leaders for their region&nbsp;and be experts on the business landscape for their region as well as in the&nbsp;specialty of bone biologics.</li><li>Regular updates to sales leadership will be required. This will be done through&nbsp;strategic account mapping and consistent updates to the pipeline and business&nbsp;plan documents.</li></ul><p><span style=\"color: rgb(143, 204, 69);\">Compensation Information</span></p><p>Base: $130-145k</p><p>Variable: Uncapped 2.5-5% on all products from dollar 1.&nbsp;</p><p>An initial Guarantee will be provided for the first 3-6 mo.&nbsp;</p><p>&nbsp;</p><p><span style=\"color: rgb(143, 204, 69);\">Location</span></p><ul><li>The territory is listed below</li><li>The candidate location is within the territory, preferably by a major airport</li></ul><p><br></p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary Only",
        "primaryFunction": "Sales",
        "travelPercentage": "25-50%",
        "minCompensation": 130,
        "maxCompensation": 145,
        "maxSalary": 145,
        "minSalary": 130,
        "featured": false,
        "applicationUrl": "https://microsite.instabot.io/zzm4L?s=105",
        "employmentType": null,
        "isRemote": true,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Western United States, USA",
        "employer": {
            "name": "Floodgate Medical",
            "id": 7846,
            "image": "https://prod-medreps.s3.amazonaws.com/7846_c49fcfbbf6.png",
            "description": "<p>FloodGate Medical is the leading talent acquisition solution in the medical industry.&nbsp;After 20 years in the medical recruiting space, our FloodGate team has completely reinvented the recruiting process through constant evolution, technology innovation, and&nbsp;customized solutions.</p><p>&nbsp;</p><p>Headquartered in Tampa, FL with a broad national presence, we engage in high-powered talent acquisition and candidate representation by partnering with the top medical companies nationwide.</p><p>&nbsp;</p><p>FloodGate seamlessly integrates the perfect blend of human experience and cutting-edge technology, using our proprietary cloud-based Talent Web App, to obsessively find and match the best candidates to the best jobs, quickly and painlessly.</p><p>&nbsp;</p><p>Above all else, our ultimate goal and mission is to improve lives by uniting great people with great companies.</p><p>&nbsp;</p>",
            "website": "https://floodgatemedical.com/"
        }
    },
    {
        "id": 2,
        "jobCode": "tjpsgBR",
        "title": "Territory Sales Manager",
        "description": "<p>Client is a global leader in advanced noninvasive neurostimulation treatments for mental health disorders. The Company is boldly advancing neuroscience with its proprietary platform technology to improve health and transform lives. Responsible for calling on physician offices and selling this piece of capital equipment</p><h1>Benefits</h1><p>Salary Commissions Car Allowance Complete health benefits</p><h1>Qualifications</h1><p>Stable, successful sales, ideally from a physician based selling environment. May consider superstar b2b reps</p><p><br></p><p>Territory is CO/UT/NM/MO/NE/MN/WY and the Dakotas, @50% travel</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Business Development",
        "travelPercentage": "25-50%",
        "minCompensation": 180,
        "maxCompensation": 200,
        "maxSalary": 90,
        "minSalary": 80,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Capital Equipment",
        "address": "Minneapolis, MN, USA",
        "employer": {
            "name": "Recruiting Company",
            "id": 28,
            "image": "",
            "description": null,
            "website": null,
            "address": "Baltimore, MD 21201, USA"
        }
    },
    {
        "id": 3,
        "jobCode": "",
        "title": "OR Sales / Hunter Device Rep Needed / Top Reps Making $500K+ and Average Reps Making $240K+",
        "description": "<ul><li>Looking for proven medical device rep with a documented track record of success</li><li>Hunter / challenger mentality</li><li>Last 3 years the average rep has made ~$230K, in FY '23 the average rep made $245K</li><li>Top reps making $500K+</li><li>Sell market leading technology in OR / surgery</li><li>Global market leading company with great career development opportunities</li><li>Territory Geography:  Greater Tulsa, OK market, and NW Arkansas</li><li>Candidates need to leave in greater Tulsa, OK market </li><li>COVID vaccination &amp; boost REQUIRED</li><li>Bachelor's degree REQUIRED</li><li>Clean Motor Vehicle Record for the past 3 years REQUIRED</li></ul>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "25-50%",
        "minCompensation": 245,
        "maxCompensation": 245,
        "maxSalary": 85,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Tulsa, OK, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 4,
        "jobCode": "",
        "title": "Associate Sales Rep / Surgical  / Market Leader ",
        "description": "<ul><li>GREAT COMPANY WITH CAREER DEVELOPMENT !</li><li>Need 1+ years of outside sales experience</li><li>$70-$90K total comp (based on years of outside sales experience).</li><li>Developmental pathway to promotion to 'full rep' ($180K-$300K)</li><li>Position open due to previous associate rep promoted</li><li>Supporting customers in a procedural / OR setting</li><li>Market leading, global company with clearly defined career development opportunities</li><li>50-75% travel</li><li>Company car, gas card / all expenses paid (including air travel when needed) , extensive benefits</li><li>REQUIRED: COVID vaccinated &amp; clean driving record for past 3 years</li><li>REQUIRED: Bachelor's Degree</li></ul>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 80,
        "maxCompensation": 80,
        "maxSalary": 72,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Indianapolis, IN, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 5,
        "jobCode": "",
        "title": "Associate Sales Rep / Surgical  / Market Leader ",
        "description": "<ul><li>GREAT COMPANY WITH CAREER DEVELOPMENT !</li><li>Need 1+ years of outside sales experience</li><li>$70-$90K total comp (based on years of outside sales experience).</li><li>Developmental pathway to promotion to 'full rep' ($180K-$300K)</li><li>Position open due to previous associate rep promoted</li><li>Supporting customers in a procedural / OR setting</li><li>Market leading, global company with clearly defined career development opportunities</li><li>50-75% travel</li><li>Company car, gas card / all expenses paid (including air travel when needed) , extensive benefits</li><li>REQUIRED: COVID vaccinated &amp; clean driving record for past 3 years</li><li>REQUIRED: Bachelor's Degree</li></ul>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 80,
        "maxCompensation": 80,
        "maxSalary": 72,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Dayton, OH, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 6,
        "jobCode": "",
        "title": "Associate Sales Rep / Surgical  / Market Leader ",
        "description": "<ul><li>GREAT COMPANY WITH CAREER DEVELOPMENT !</li><li>Need 1+ years of outside sales experience</li><li>$70-$90K total comp (based on years of outside sales experience).</li><li>Developmental pathway to promotion to 'full rep' ($180K-$300K)</li><li>Position open due to previous associate rep promoted</li><li>Supporting customers in a procedural / OR setting</li><li>Market leading, global company with clearly defined career development opportunities</li><li>50-75% travel</li><li>Company car, gas card / all expenses paid (including air travel when needed) , extensive benefits</li><li>REQUIRED: COVID vaccinated &amp; clean driving record for past 3 years</li><li>REQUIRED: Bachelor's Degree</li></ul>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 80,
        "maxCompensation": 80,
        "maxSalary": 72,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Columbus, OH, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 7,
        "jobCode": "",
        "title": "Associate Sales Rep / Surgical  / Market Leader ",
        "description": "<ul><li>GREAT COMPANY WITH CAREER DEVELOPMENT !</li><li>Need 1+ years of outside sales experience</li><li>$70-$90K total comp (based on years of outside sales experience).  </li><li>Developmental pathway to promotion to 'full rep' ($180K-$300K)</li><li>Position open due to previous associate rep promoted</li><li>Supporting customers in a procedural / OR setting</li><li>Market leading, global company with clearly defined career development opportunities</li><li>50-75% travel</li><li>Company car, gas card / all expenses paid (including air travel when needed) , extensive benefits</li><li>REQUIRED: COVID vaccinated &amp; clean driving record for past 3 years</li><li>REQUIRED: Bachelor's Degree</li></ul>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 80,
        "maxCompensation": 80,
        "maxSalary": 72,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Cincinnati, OH, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 8,
        "jobCode": "Ultrasound - New Mexico/West Texas",
        "title": "San Antonio/Austin  - Ultrasound",
        "description": "<p>Selling \"new\" innovative Ultrasound technology to point of care segments in Hospitals for industry leader.</p><p><br></p><p>Great products, phenomenal leadership and aggressive comp plan</p><p><br></p><p>Phenomenal job!</p><p><br></p><p>Will look at hospital reps with capital sales experience but must prospect on daily basis. Ideally selling in a transactional sales enviroment.</p><p><br></p><p>Looking for candidates based in San Antonio or Austin.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 235,
        "maxCompensation": 250,
        "maxSalary": 75,
        "minSalary": 75,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Capital Equipment",
        "address": "San Antonio, TX, USA",
        "employer": {
            "name": "Medisearch",
            "id": 2205,
            "image": "https://prod-medreps.s3.amazonaws.com/2205_72eb74fb3e.png",
            "description": null,
            "website": null,
            "address": "San Francisco, CA 94101, USA"
        }
    },
    {
        "id": 9,
        "jobCode": "NMGAVA",
        "title": "Sales Rep",
        "description": "<p>Our client is an industry leader<span style=\"color: rgb(95, 99, 104);\">&nbsp;of medical and surgical instrument sterilization, disinfection, and cleaning products and services.</span></p><p><br></p><p>Qualified Candidates need solid B-2-B outside sales experience with a proven track record and/or light medical.</p><p><br></p><p><strong>Nikki Greenberg</strong></p><p>BRG &amp; Assoc.</p><p>703-606-0070</p><p><a href=\"https://mailto:NicoleMGreenberg@gmail.com\" rel=\"noopener noreferrer\" target=\"_blank\">NicoleMGreenberg@gmail.com</a></p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "25-50%",
        "minCompensation": 120,
        "maxCompensation": 130,
        "maxSalary": 65,
        "minSalary": 62,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "Fairfax, VA, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 10,
        "jobCode": "BGDB22224",
        "title": "Clinical Cath Lab Specialist",
        "description": "<p>Clinical support of the sales team through product demos and clinical education.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Not Specified",
        "primaryFunction": "Clinical Consulting",
        "travelPercentage": "25-50%",
        "minCompensation": 140,
        "maxCompensation": 150,
        "maxSalary": 110,
        "minSalary": 100,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Columbia, MD, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 11,
        "jobCode": "BGDB22224",
        "title": "Clinical Cath Lab Specialist",
        "description": "<p>Clinical support of the sales team through product demos and clinical education.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Not Specified",
        "primaryFunction": "Clinical Consulting",
        "travelPercentage": "25-50%",
        "minCompensation": 140,
        "maxCompensation": 150,
        "maxSalary": 110,
        "minSalary": 100,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Fairfax, VA, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 12,
        "jobCode": "NMGANOK",
        "title": "Neuro Sales Representative",
        "description": "<p>We are currently recruiting for a reputable medical device manufacturer. This is a opportunity within the Neurosurgery Division.</p><p><br></p><p>Qualified Candidates have a minimum of 2 years sales experience with Hospital or device sales</p><p><br></p><p>Full Corporate Benefits &amp; Company Car</p><p>2-3 years of sales experience with some exposure to hospitals as a call point.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "25-50%",
        "minCompensation": 140,
        "maxCompensation": 150,
        "maxSalary": 68,
        "minSalary": 58,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "Oklahoma City, OK, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 13,
        "jobCode": "NMGKY",
        "title": "Surgical Sales Specialist",
        "description": "<p>Selling surgical products and services into the hospital.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "0-25%",
        "minCompensation": 125,
        "maxCompensation": 130,
        "maxSalary": 63,
        "minSalary": 60,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": true,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "Lexington, KY, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 14,
        "jobCode": "BGEBOST",
        "title": "Clinical Specialist",
        "description": "<p>Clinical support of the sales team. These responsibilities include education of clinicians, in-service education programs, ongoing observation\\feedback on device implant for improvement.</p><p><br></p><p>Requirements include current clinical support experience and a work history in interventional cardiology/cardiac cath lab, imaging experience (sonography\\ultrasound)</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales Support",
        "travelPercentage": "25-50%",
        "minCompensation": 175,
        "maxCompensation": 200,
        "maxSalary": 140,
        "minSalary": 130,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "Atlanta, GA, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 15,
        "jobCode": "NMGASF",
        "title": "Sales Rep",
        "description": "<p>Our client is an industry leader<span style=\"color: rgb(95, 99, 104);\">&nbsp;of medical and surgical instrument sterilization, disinfection, and cleaning products and services.</span></p><p><br></p><p>Qualified Candidates need solid B-2-B outside sales experience with a proven track record and/or light medical.</p><p><br></p><p><strong>Nikki Greenberg</strong></p><p>BRG &amp; Assoc.</p><p>703-606-0070</p><p><a href=\"https://mailto:NicoleMGreenberg@gmail.com\" rel=\"noopener noreferrer\" target=\"_blank\">NicoleMGreenberg@gmail.com</a></p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "25-50%",
        "minCompensation": 120,
        "maxCompensation": 130,
        "maxSalary": 74,
        "minSalary": 65,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "San Fernando, CA, USA",
        "employer": {
            "name": "BRG & Associates",
            "id": 1617,
            "image": "",
            "description": "",
            "website": "",
            "address": "Fairfax Station, VA 22039, USA"
        }
    },
    {
        "id": 16,
        "jobCode": "",
        "title": "Territory Manager - Biomedical (Michigan/Indiana)",
        "description": "<p><strong>Job Overview:</strong></p><p>We are seeking an experienced and results-driven Biomed Sales Representative to join our dynamic team. Our client is a single source provider of medical, surgical, diagnostic imaging, and ultrasound equipment, including sales, service, repair, parts, refurbishing, and installation. Making it easier and more affordable for every hospital, clinic, and medical practice to have the very best equipment, supplies and service. The ideal candidate will be responsible for developing and executing strategic sales plans to achieve or exceed sales targets within an assigned territory. The role requires a strong understanding of medical devices and capital equipment, excellent interpersonal skills, and the ability to build and maintain relationships with healthcare professionals.</p><p><strong>&nbsp;</strong></p><p><strong>Responsibilities:</strong></p><p>1.&nbsp;&nbsp;&nbsp;<strong>Territory Management:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Territory: Michigan/Indiana (Detroit &amp; Indianapolis)</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expected Travel: 50%</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ideally in the field 4+ Days a week</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Develop and implement a comprehensive territory sales plan to achieve revenue and market share goals.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Analyze market trends, customer needs, and competitor activities to identify new business opportunities.</p><p><br></p><p>2.&nbsp;&nbsp;&nbsp;<strong>Sales and Relationship Building:</strong></p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cultivate strong relationships with key decision-makers, including physicians, surgeons, nurses, and other healthcare professionals.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conduct product demonstrations and presentations to showcase the benefits of our medical devices.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Collaborate with healthcare providers to understand their needs and recommend appropriate solutions.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Call Points: Acute Care, Biomed, Radiology, Cath Lab, VP of Imaging, Supply Chain, Contracting, Service Line Coordinators</p><p><br></p><p>3.&nbsp;&nbsp;&nbsp;<strong>Customer Education:</strong></p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Provide training and education sessions to healthcare professionals on the proper use and benefits of our medical devices.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Stay updated on industry trends, clinical studies, and advancements to effectively communicate product value.</p><p><br></p><p>4.&nbsp;&nbsp;&nbsp;<strong>Sales Forecasting and Reporting:</strong></p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Track and report on sales activities, customer feedback, and market trends within the territory.</p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Utilize CRM tools to maintain accurate and up-to-date customer information.</p><p><br></p><p><br></p><p>5.&nbsp;&nbsp;&nbsp;<strong>Cross-functional Collaboration:</strong></p><p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Collaborate with internal teams, including marketing, customer support, and product development, to ensure alignment with customer needs and market trends.</p><p><strong>Qualifications:</strong></p><ul><li>Bachelor's degree in Business, Marketing, or a related field.</li><li>Proven experience in medical device sales, preferably with a focus on Diagnostics/Blood Cultures.</li><li>Strong knowledge of the healthcare industry, including regulatory requirements and compliance.</li><li>Excellent communication and presentation skills.</li><li>Ability to work independently and collaboratively in a team environment.</li><li>Results-driven with a track record of meeting or exceeding sales targets.</li><li>Willingness to travel within the assigned territory.</li></ul><p><strong>&nbsp;</strong></p><p><strong>Benefits &amp; Compensation:</strong></p><ul><li>Competitive salary and commission structure.</li><li>$70K base + $70K variable = $140K at plan</li><li>Uncapped plan, many reps in the $230-240K range</li><li>6-month guarantee</li><li>Comprehensive health and dental benefits.</li><li>Car allowance and travel reimbursement.</li><li>Opportunities for professional development and advancement.</li></ul><p><br></p><p>If you are a motivated and goal-oriented individual with a passion for medical device sales, we invite you to apply and contribute to our commitment to improving healthcare outcomes through innovative solutions.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "50-75%",
        "minCompensation": 140,
        "maxCompensation": 140,
        "maxSalary": 70,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Capital Equipment",
        "address": "Detroit, MI, USA",
        "employer": {
            "name": "Accordance Search Group",
            "id": 4137,
            "image": "https://prod-medreps.s3.amazonaws.com/4137_056a026644.png",
            "description": null,
            "website": null,
            "address": "Portland, OR 97201, USA"
        }
    },
    {
        "id": 17,
        "jobCode": "TC-IN-AT",
        "title": "Medical Device Sales Representative                                                                                                           *NEW*",
        "description": "<p><strong>Medical Device Sales Representative- $125K+</strong></p><p><br></p><p>An innovative and progressive Medical Device Manufacturer is seeking an energetic, self-motivated, assertive \"sales superstar\" to sell medical devices and capital equipment into key hospital accounts. We are seeking a Healthcare/Hospital Sales Executive to call into hospitals, IDNs, and key health systems.</p><p><br></p><p>First year total compensation =&nbsp;<strong>$125K+</strong>&nbsp;all expenses covered, excellent benefits &amp; corporate training. Numerous opportunities for growth. Submit resume in WORD format for immediate consideration.</p><p><br></p><p>**Must have 2+ years healthcare/hospital sales experience</p><p>**Four-year degree</p><p>**Drive and determination to the BEST with income expectations well into the 6 figures.</p><p>**Documented track record of sales success</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "0-25%",
        "minCompensation": 125,
        "maxCompensation": 150,
        "maxSalary": 80,
        "minSalary": 80,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": false,
        "productCategory": "Medical Device",
        "address": "Allentown, PA, USA",
        "employer": {
            "name": "Med-Search Recruiting Network, Inc.",
            "id": 1682,
            "image": "https://prod-medreps.s3.amazonaws.com/1682_f3c93d1e4f.png",
            "description": "<p><span style=\"color:black;\">We are a National Search firm specializing in Healthcare Sales, Sales Management, Marketing, Diversity, and Executive Management Recruiting.</span></p><p>&nbsp;</p><p><span style=\"color:black;\">The Med-Search team continues the commitment of serving clients with game-changing recruiting solutions utilizing cutting-edge technologies, proficient sourcing practices, and trusted relationships.</span></p><p>&nbsp;</p><p><span style=\"color:black;\">Med-Search Recruiting is headquartered in St. Louis, Missouri, with 71 affiliate offices covering all 50 states. We remain the hiring experts focused on delivering the highest quality and personalized service. 25+ years in business! www.medrecruiters.com</span></p>",
            "website": "",
            "address": "Saint Louis, MO 63101, USA"
        }
    },
    {
        "id": 18,
        "jobCode": "EL30473P6G4",
        "title": "Associate Spine Sales Representative",
        "description": "<p>We are working on a great opportunity with a medical device company. Responsibilities will include but are not limited to: • Develop relationships with key spine surgeons. Communicate with customer accounts regarding a variety of topics, including product updates, changes to product portfolio, and educational programs. • Assist the Spine Specialist during cases as well as on field calls within the assigned geography. • Ensure that all surgical sets/trays are restocked and prepared for future surgical cases. • Follow-up after surgery cases to resolve any open issues and close surgeons on use of the products.</p><h1>Benefits</h1><p>Full benefit package with expense account and car allowance.</p><h1>Qualifications</h1><p>Our client is looking for a candidate with 1-2 years of general outside (B2B) business to business sales experience. Strong selling skills with a proven track record and an ability to make sales presentations with positive results. Candidates must have a bachelor's degree.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Business Development",
        "travelPercentage": "0-25%",
        "minCompensation": 130,
        "maxCompensation": 150,
        "maxSalary": 80,
        "minSalary": 70,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": true,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Sacramento, CA, USA",
        "employer": {
            "name": "CPR4sales",
            "id": 52,
            "image": "https://prod-medreps.s3.amazonaws.com/52_876ca2f5a5.png",
            "description": null,
            "website": null,
            "address": "Charlotte, NC 28201, USA"
        }
    },
    {
        "id": 19,
        "jobCode": "DT",
        "title": "Orthopedic Image Guidance Device Sales Position",
        "description": "<p>Orthopedic Surgeon preference device sales position for Image Guidance. Client is expanding due to success, targeting young, ambitious, successful Orthopedic Trauma, Total Hip or Knee Representatives.</p><p>The successful candidate will have 1-3 years of current or very recent Hip or Knee Sales Experience having previously been a Collegiate Athlete or Member of the Military.</p><p>Income comes with an uncapped bonus.</p><p>Experience with VAC &amp; Product Approval process needed as well.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "0-25%",
        "minCompensation": 150,
        "maxCompensation": 155,
        "maxSalary": 95,
        "minSalary": 90,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Lansing, MI, USA",
        "employer": {
            "name": "Dorr and Associates",
            "id": 423,
            "image": "",
            "description": "<p>Placement of both Sales Representatives as well as Sales Managers throughout the Vertical Medical Sales Marketplace. Concentrated Areas include all areas of the Operating Room &amp; Cath Lab.</p>",
            "website": null,
            "address": "Saint Louis, MO 63101, USA"
        }
    },
    {
        "id": 20,
        "jobCode": "DT",
        "title": "Orthopedic Image Guidance Device Sales Position",
        "description": "<p>Orthopedic Surgeon preference device sales position for Image Guidance. Client is expanding due to success, targeting young, ambitious, successful Orthopedic Trauma, Total Hip or Knee Representatives.</p><p>The successful candidate will have 1-3 years of current or very recent Hip or Knee Sales Experience having previously been a Collegiate Athlete or Member of the Military.</p><p>Income comes with an uncapped bonus.</p><p>Experience with VAC &amp; Product Approval process needed as well.</p>",
        "slug": 1641663,
        "datePosted": "March 28th, 2024",
        "dateExpires": "Apr 24th, 2024",
        "compensationType": "Salary + Commission",
        "primaryFunction": "Sales",
        "travelPercentage": "0-25%",
        "minCompensation": 150,
        "maxCompensation": 155,
        "maxSalary": 95,
        "minSalary": 90,
        "featured": false,
        "applicationUrl": null,
        "employmentType": null,
        "isRemote": false,
        "isFieldBased": true,
        "productCategory": "Medical Device",
        "address": "Grand Rapids, MI, USA",
        "employer": {
            "name": "Dorr and Associates",
            "id": 423,
            "image": "",
            "description": "<p>Placement of both Sales Representatives as well as Sales Managers throughout the Vertical Medical Sales Marketplace. Concentrated Areas include all areas of the Operating Room &amp; Cath Lab.</p>",
            "website": null,
            "address": "Saint Louis, MO 63101, USA"
        }
    }
]